apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-eventing.v0.2.1
spec:
  displayName: Knative Eventing
  description: |
    Kubernetes-native Eventing resource
  version: 0.2.1
  maturity: alpha
  replaces: knative-eventing.v0.2.0

  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: default
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'

      deployments:
      - name: eventing-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: eventing-controller
          template:
            metadata:
              labels:
                app: eventing-controller
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                - --experimentalControllers=subscription.eventing.knative.dev
                image: quay.io/openshift-knative/knative-0.2:knative-eventing-controller
                name: eventing-controller
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/bbf0c91/etc/hacks/knative-eventing-0.2.1.yaml']
              serviceAccountName: default
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

      - name: webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webhook
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: webhook
                role: webhook
            spec:
              containers:
              - image: quay.io/openshift-knative/knative-0.2:knative-eventing-webhook
                name: webhook
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: default
              volumes:
              - configMap:
                  name: config-logging
                name: config-logging

      - name: in-memory-channel-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: controller
          template:
            metadata:
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: controller
            spec:
              containers:
              - image: quay.io/openshift-knative/knative-0.2:knative-eventing-in-memory-channel-controller
                name: controller
              serviceAccountName: default

      - name: in-memory-channel-dispatcher
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: dispatcher
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: dispatcher
            spec:
              containers:
              - args:
                - --sidecar_port=8080
                - --config_map_noticer=watcher
                - --config_map_namespace=knative-eventing
                - --config_map_name=in-memory-channel-dispatcher-config-map
                image: quay.io/openshift-knative/knative-0.2:knative-eventing-fanoutsidecar
                name: dispatcher
              serviceAccountName: default

  customresourcedefinitions:
    owned:
      - name: channels.eventing.knative.dev
        kind: Channel
        description: Channel
        displayName: Channel
        version: v1alpha1
      - name: clusterchannelprovisioners.eventing.knative.dev
        kind: ClusterChannelProvisioner
        description: ClusterChannelProvisioner
        displayName: ClusterChannelProvisioner
        version: v1alpha1
      - name: subscriptions.eventing.knative.dev
        kind: Subscription
        description: Subscription
        displayName: Subscription
        version: v1alpha1
      - name: containersources.sources.eventing.knative.dev
        kind: ContainerSource
        description: ContainerSource
        displayName: ContainerSource
        version: v1alpha1
      - name: githubsources.sources.eventing.knative.dev
        kind: GitHubSource
        description: GitHubSource
        displayName: GitHubSource
        version: v1alpha1
      - name: kuberneteseventsources.sources.eventing.knative.dev
        kind: KubernetesEventSource
        description: KubernetesEventSource
        displayName: KubernetesEventSource
        version: v1alpha1
