apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-eventing.v0.2.1
spec:
  displayName: Knative Eventing
  description: |
    Kubernetes-native Eventing resource
  version: 0.2.1
  maturity: alpha
  replaces: knative-eventing.v0.2.0

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: default
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'

      deployments:
      - name: eventing-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: eventing-controller
          template:
            metadata:
              labels:
                app: eventing-controller
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                - --experimentalControllers=subscription.eventing.knative.dev
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/controller@sha256:3486cb9d337b829907532e78c8098b6680fbe3aa10a0aa81e7db327bb8980640
                name: eventing-controller
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/master/etc/hacks/knative-eventing-0.2.1.yaml']
              serviceAccountName: default
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

      - name: webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webhook
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: webhook
                role: webhook
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/cmd/webhook@sha256:1ec64e26ed2b8895e783e9c1a07a11376dcb244f75ad166b2b116f124b2f2d44
                name: webhook
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: default
              volumes:
              - configMap:
                  name: config-logging
                name: config-logging

      - name: in-memory-channel-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: controller
          template:
            metadata:
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: controller
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller@sha256:85a6954a9ab118872f6826425b213e57589de8f9f2ac97d31aef5d5022104532
                name: controller
              serviceAccountName: default

      - name: in-memory-channel-dispatcher
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: dispatcher
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: dispatcher
            spec:
              containers:
              - args:
                - --sidecar_port=8080
                - --config_map_noticer=watcher
                - --config_map_namespace=knative-eventing
                - --config_map_name=in-memory-channel-dispatcher-config-map
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/fanoutsidecar@sha256:a04bdbe0ffad3c47286ebfb961648e9f1d2b366aea243e9ea1ae591e706de06d
                name: dispatcher
              serviceAccountName: default

  customresourcedefinitions:
    owned:
      - name: channels.eventing.knative.dev
        kind: Channel
        description: Channel
        displayName: Channel
        version: v1alpha1
      - name: clusterchannelprovisioners.eventing.knative.dev
        kind: ClusterChannelProvisioner
        description: ClusterChannelProvisioner
        displayName: ClusterChannelProvisioner
        version: v1alpha1
      - name: subscriptions.eventing.knative.dev
        kind: Subscription
        description: Subscription
        displayName: Subscription
        version: v1alpha1
      - name: containersources.sources.eventing.knative.dev
        kind: ContainerSource
        description: ContainerSource
        displayName: ContainerSource
        version: v1alpha1
      - name: githubsources.sources.eventing.knative.dev
        kind: GitHubSource
        description: GitHubSource
        displayName: GitHubSource
        version: v1alpha1
      - name: kuberneteseventsources.sources.eventing.knative.dev
        kind: KubernetesEventSource
        description: KubernetesEventSource
        displayName: KubernetesEventSource
        version: v1alpha1
