apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-eventing.v0.3.0
spec:
  displayName: Knative Eventing
  description: |
    Kubernetes-native Eventing resource
  version: 0.3.0
  maturity: alpha
  replaces: knative-eventing.v0.2.1

  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: default
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
      - serviceAccountName: eventing-controller
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
      - serviceAccountName: in-memory-channel-controller
        rules:
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          - channels/status
          - clusterchannelprovisioners
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - eventing.knative.dev
          resources:
          - '*/finalizers'
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          verbs:
          - get
          - list
          - watch
          - create
        - apiGroups:
          - ""
          resourceNames:
          - in-memory-channel-clusterbus
          resources:
          - services
          verbs:
          - delete
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - update
        - apiGroups:
          - ""
          resourceNames:
          - in-memory-channel-dispatcher-config-map
          resources:
          - configmaps
          verbs:
          - update
        - apiGroups:
          - networking.istio.io
          resources:
          - virtualservices
          verbs:
          - get
          - list
          - watch
          - create
          - update
      - serviceAccountName: in-memory-channel-dispatcher
        rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch

        # The above rules are from upstream. The remaining are
        # required for OpenShift

        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged

      deployments:
      - name: eventing-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: eventing-controller
          template:
            metadata:
              labels:
                app: eventing-controller
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                - --experimentalControllers=subscription.eventing.knative.dev
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/controller@sha256:ecefa8fb0de1bb69ddfc13a212424d4d09232dc566c3653810c20bbf3ef80aa7
                name: eventing-controller
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/master/etc/hacks/knative-eventing-0.3.0.yaml']
              serviceAccountName: eventing-controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

      - name: webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webhook
              role: webhook
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: webhook
                role: webhook
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/cmd/webhook@sha256:3391e2dfc6461261be18739adcddaf69ba8e5643d1ebfac3b7b6a80c9907104c
                name: webhook
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: eventing-controller
              volumes:
              - configMap:
                  name: config-logging
                name: config-logging

      - name: in-memory-channel-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: controller
          template:
            metadata:
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: controller
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller@sha256:6452c0ecc6099c5a7a6b9f94763c982ec77ed5c9e560619362a8573629dc67dd
                name: controller
              serviceAccountName: in-memory-channel-controller

      - name: in-memory-channel-dispatcher
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: dispatcher
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: dispatcher
            spec:
              containers:
              - args:
                - --sidecar_port=8080
                - --config_map_noticer=watcher
                - --config_map_namespace=knative-eventing
                - --config_map_name=in-memory-channel-dispatcher-config-map
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/fanoutsidecar@sha256:a1c331166249dd82d78dffb26ad89e9c592a13a88b9283ab2a2603629579e3ef
                name: dispatcher
              serviceAccountName: in-memory-channel-dispatcher

  customresourcedefinitions:
    owned:
      - name: channels.eventing.knative.dev
        kind: Channel
        description: Channel
        displayName: Channel
        version: v1alpha1
      - name: clusterchannelprovisioners.eventing.knative.dev
        kind: ClusterChannelProvisioner
        description: ClusterChannelProvisioner
        displayName: ClusterChannelProvisioner
        version: v1alpha1
      - name: subscriptions.eventing.knative.dev
        kind: Subscription
        description: Subscription
        displayName: Subscription
        version: v1alpha1
      - name: containersources.sources.eventing.knative.dev
        kind: ContainerSource
        description: ContainerSource
        displayName: ContainerSource
        version: v1alpha1
      - name: githubsources.sources.eventing.knative.dev
        kind: GitHubSource
        description: GitHubSource
        displayName: GitHubSource
        version: v1alpha1
      - name: kuberneteseventsources.sources.eventing.knative.dev
        kind: KubernetesEventSource
        description: KubernetesEventSource
        displayName: KubernetesEventSource
        version: v1alpha1
      - name: cronjobsources.sources.eventing.knative.dev
        kind: CronJobSource
        description: CronJobSource
        displayName: CronJobSource
        version: v1alpha1
