apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-build.v0.2.0
spec:
  displayName: Knative Build
  description: |
    Kubernetes-native Build resource
  version: 0.2.0
  maturity: alpha
  replaces: knative-build.v0.1.2

  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces

  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: build-controller
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          - secrets
          - events
          - services
          - serviceaccounts
          - configmaps
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - caching.internal.knative.dev
          resources:
          - images
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - patch
          - watch
      clusterPermissions:
      - serviceAccountName: build-controller
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
      deployments:
      - name: build-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: build-controller
          template:
            metadata:
              labels:
                app: build-controller
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                - -creds-image
                - quay.io/openshift-knative/knative-0.2:knative-build-creds-init
                - -git-image
                - quay.io/openshift-knative/knative-0.2:knative-build-git-init
                - -nop-image
                - quay.io/openshift-knative/knative-0.2:knative-build-nop
                env:
                - name: SYSTEM_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/openshift-knative/knative-0.2:knative-build-controller
                name: build-controller
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/bbf0c91/etc/hacks/knative-build-0.2.0.yaml']
              serviceAccountName: build-controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging
      - name: build-webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: build-webhook
          template:
            metadata:
              labels:
                app: build-webhook
                role: build-webhook
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                env:
                - name: SYSTEM_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/openshift-knative/knative-0.2:knative-build-webhook
                name: build-webhook
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: build-controller
              volumes:
              - configMap:
                  name: config-logging
                name: config-logging
  customresourcedefinitions:
    owned:
      - description: Create and run on-cluster processes to completion
        displayName: Build
        kind: Build
        name: builds.build.knative.dev
        version: v1alpha1
      - description: Encapsulates a configurable, reusable build process
        displayName: Build Template
        kind: BuildTemplate
        name: buildtemplates.build.knative.dev
        version: v1alpha1
      - description: Encapsulates a cluster-scoped build process
        displayName: Cluster Build Template
        kind: ClusterBuildTemplate
        name: clusterbuildtemplates.build.knative.dev
        version: v1alpha1
      - description: A cached build image?
        displayName: Image
        kind: Image
        name: images.caching.internal.knative.dev
        version: v1alpha1
