apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: knative-eventing.v0.2.0
spec:
  displayName: Knative Eventing
  description: |
    Kubernetes-native Eventing resource
  version: 0.2.0
  maturity: alpha

  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: in-memory-channel-controller
        rules:
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          - clusterchannelprovisioners
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          verbs:
          - get
          - list
          - watch
          - create
        - apiGroups:
          - ""
          resourceNames:
          - in-memory-channel-dispatcher-config-map
          resources:
          - configmaps
          verbs:
          - update
        - apiGroups:
          - networking.istio.io
          resources:
          - virtualservices
          verbs:
          - get
          - list
          - watch
          - create
      - serviceAccountName: in-memory-channel-dispatcher
        rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
      clusterPermissions:
      - serviceAccountName: eventing-controller
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
      deployments:
      - name: eventing-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: eventing-controller
          template:
            metadata:
              labels:
                app: eventing-controller
            spec:
              containers:
              - args:
                - -logtostderr
                - -stderrthreshold
                - INFO
                - --experimentalControllers=subscription.eventing.knative.dev
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/controller@sha256:bfb8bf951f2ccead13e5d999f3c8e44a5c815f89eef03391aa061e19407bcd9b
                name: eventing-controller
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              initContainers:
              - name: olm-hack
                image: lachlanevenson/k8s-kubectl
                args: ['apply', '-f', 'https://raw.githubusercontent.com/openshift-cloud-functions/knative-operators/master/etc/hacks/knative-eventing-0.2.0.yaml']
              serviceAccountName: eventing-controller
              volumes:
              - configMap:
                  name: config-logging
                  optional: true
                name: config-logging

      - name: webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webhook
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
              labels:
                app: webhook
                role: webhook
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/cmd/webhook@sha256:0c8e6180481663045088cebea41cfbf92ef590da748b92bed77a8c0dc2539bff
                name: webhook
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                - mountPath: /etc/config-logging
                  name: config-logging
              serviceAccountName: eventing-controller
              volumes:
              - configMap:
                  name: config-logging
                name: config-logging

      - name: in-memory-channel-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: controller
          template:
            metadata:
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: controller
            spec:
              containers:
              - image: gcr.io/knative-releases/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller@sha256:cbc86e2faa593cdd34c2ed54fd171fcbed4bfa26017c1e7db554c584162a8846
                name: controller
              serviceAccountName: in-memory-channel-controller

      - name: in-memory-channel-dispatcher
        spec:
          replicas: 1
          selector:
            matchLabels:
              clusterChannelProvisioner: in-memory-channel
              role: dispatcher
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
              labels:
                clusterChannelProvisioner: in-memory-channel
                role: dispatcher
            spec:
              containers:
              - args:
                - --sidecar_port=8080
                - --config_map_noticer=watcher
                - --config_map_namespace=knative-eventing
                - --config_map_name=in-memory-channel-dispatcher-config-map
                image: gcr.io/knative-releases/github.com/knative/eventing/cmd/fanoutsidecar@sha256:b57a317067d9a4299f08f6b05f161e50c8ac9b5e2cca812c41a938ad8b12ab38
                name: dispatcher
              serviceAccountName: in-memory-channel-dispatcher

  customresourcedefinitions:
    owned:
      - name: channels.eventing.knative.dev
        kind: Channel
        description: Channel
        displayName: Channel
        version: v1alpha1
      - name: clusterchannelprovisioners.eventing.knative.dev
        kind: ClusterChannelProvisioner
        description: ClusterChannelProvisioner
        displayName: ClusterChannelProvisioner
        version: v1alpha1
      - name: subscriptions.eventing.knative.dev
        kind: Subscription
        description: Subscription
        displayName: Subscription
        version: v1alpha1
      - name: containersources.sources.eventing.knative.dev
        kind: ContainerSource
        description: ContainerSource
        displayName: ContainerSource
        version: v1alpha1
      - name: githubsources.sources.eventing.knative.dev
        kind: GitHubSource
        description: GitHubSource
        displayName: GitHubSource
        version: v1alpha1
      - name: kuberneteseventsources.sources.eventing.knative.dev
        kind: KubernetesEventSource
        description: KubernetesEventSource
        displayName: KubernetesEventSource
        version: v1alpha1
